import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';
import Wallet from './wallet';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dapp Test</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/icon.svg" rel="icon" type="image/x-icon"/>
      </Head>

      <main className={styles.main}>
        <Wallet />
        
      </main>

      <footer className={styles.footer}>
        <a href="https://opensea.io/collection/voodoo-labs-polygon" rel="noopener noreferrer" target="_blank">
          See Details On OpenSea
        </a>
      </footer>
    </div>
  );
};

export default Home;
